import { z } from 'zod';
// This file has been generated by Specta. Do not edit this file manually.
export const ConversionModeSchema = z.union([z.literal('reencode'), z.literal('remux')]);
export type ConversionMode = z.infer<typeof ConversionModeSchema>;

export const DirectoryStatsSchema = z.object({
  exists: z.boolean(),
  file_count: z.number(),
  total_size_bytes: z.number(),
  files: z.array(z.lazy(() => FileStatSchema)),
  history_skipped_count: z.number(),
  history_skipped_bytes: z.number()
});
export type DirectoryStats = z.infer<typeof DirectoryStatsSchema>;

export const EncoderCapabilitiesSchema = z.object({
  nvenc: z.boolean(),
  amf: z.boolean(),
  videotoolbox: z.boolean(),
  qsv: z.boolean()
});
export type EncoderCapabilities = z.infer<typeof EncoderCapabilitiesSchema>;

export const FileStatSchema = z.object({
  name: z.string(),
  size_bytes: z.number()
});
export type FileStat = z.infer<typeof FileStatSchema>;

export const PipelineSummarySchema = z.object({
  message: z.string(),
  original_size_bytes: z.number(),
  output_size_bytes: z.number(),
  skipped_files: z.number()
});
export type PipelineSummary = z.infer<typeof PipelineSummarySchema>;

export const PresetSchema = z.union([
  z.literal('balanced'),
  z.literal('default'),
  z.literal('fast'),
  z.literal('faster'),
  z.literal('medium'),
  z.literal('p1'),
  z.literal('p2'),
  z.literal('p3'),
  z.literal('p4'),
  z.literal('p5'),
  z.literal('p6'),
  z.literal('p7'),
  z.literal('quality'),
  z.literal('slow'),
  z.literal('slower'),
  z.literal('speed'),
  z.literal('superfast'),
  z.literal('ultrafast'),
  z.literal('veryfast'),
  z.literal('veryslow')
]);
export type Preset = z.infer<typeof PresetSchema>;

export const StorageTypeSchema = z.union([z.literal('hdd'), z.literal('ssd')]);
export type StorageType = z.infer<typeof StorageTypeSchema>;

export const VideoCodecSchema = z.union([
  z.literal('av1_amf'),
  z.literal('av1_nvenc'),
  z.literal('av1_qsv'),
  z.literal('h264_amf'),
  z.literal('h264_nvenc'),
  z.literal('h264_qsv'),
  z.literal('h264_videotoolbox'),
  z.literal('hevc_amf'),
  z.literal('hevc_nvenc'),
  z.literal('hevc_qsv'),
  z.literal('hevc_videotoolbox'),
  z.literal('libx264'),
  z.literal('libx265')
]);
export type VideoCodec = z.infer<typeof VideoCodecSchema>;

export const VideoPipelinePayloadSchema = z.object({
  input_directories: z.array(z.string()),
  file_extensions: z.string(),
  recursive: z.boolean(),
  subtitle_tracks: z.string(),
  output_extension: z.string(),
  conversion_mode: ConversionModeSchema,
  video_codec: VideoCodecSchema,
  preset: PresetSchema,
  crf: z.string(),
  reencode_concurrency: z.number(),
  remux_concurrency: z.number(),
  storage_type: StorageTypeSchema
});
export type VideoPipelinePayload = z.infer<typeof VideoPipelinePayloadSchema>;
